cat << 'EOF' > .upsun/config.yaml
applications:
  helloworld:
    type: nodejs:20
    web:
      commands:
        start: npm start

routes:
  "https://{default}/":
    type: upstream
    upstream: "helloworld:http"
EOF